version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: daffa123
      MYSQL_DATABASE: todoit
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: todoit-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:daffa123@db:3306/todoit
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: todoit-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
